### ISSUE TITLE
Use Docker Container

### ISSUE THREAD

**Issue by snlucas** [Iorjunior/floating_webcam#3]
Use Docker to make it easy to run the project.

**Comment by Iorjunior** [comment]
I tried, I was unsuccessful. both opencv and tkinter gave compatibility errors. when I solved one the other started to make mistakes. the last error I couldn't resolve 

`self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) _tkinter.TclError: in the display name and in the $DISPLAY environment variable` 

Maybe in the future I'll try again, but if you want you can try.

**Comment by snlucas** [comment]
I'll do the Dockerfile. @snlucas 
These errors have nothing to do with Docker.
Running it in my machine caused the same. So we have a bug.

**Comment by snlucas** [comment]
I've tried using Docker but it doesn't work well. I searched this, and it doesn't seem like using Docker to run the GUI is a good idea. Anyway, documentation may have a section explaining that you need to have Tkinter installed on your system.
